config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages
  resources :ideas
  root :to => "pages#index"

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ideas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def show 
  end
  def new
    @idea = Idea.new
  end
   def create
     @idea = Idea.new(idea_params)
     @idea.user = current_user
      respond_to do |format|
       if @idea.save
         format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
         format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
         format.json { render json: @idea.errors, status: :unprocessable_entity }
       end
      end
  end
  private
   def idea_params
     params.require(:idea).permit(:title,:description)
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ideas/new.html.erb
<%= form_for(@idea) do |f| %>
<% if @idea.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>
 
      <ul>
    <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
      <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VoteMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user.present? %>
  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
  <% else %>
  <%= link_to 'Sign In', new_user_session_path %> | <%= link_to 'Register Now', new_user_registration_path %>
  <% end %>
  
      <p class="notice"><%= notice %></p>                                 
       <p class="alert"><%= alert %></p>  
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h2>Hi! I'm an idea voting app!</h2>
<%= link_to "Submit an idea", new_idea_path %>